# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9824e6a8a1ed4628597505e5e808f5cd48ffcd534b58364f095d88fd8504fbc1ff01cad60b41368f6c83e494274206a6110d34174cef664c2a97a0a12a6a5e78

test:
  secret_key_base: 2e6d9bd0746c298a225b0152e5ced0b94c5a07c82b25452c34b751688f0bed3415906652162cf6d246286f97b607acc92c846ad919f2b816b8f353037dc41c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
